Description: This template deploys an S3 bucket and creates an AWS Glue IAM service role for data processing.

Parameters:
  S3BucketForETLProject: 
    Description: Please enter the name for your S3 bucket. This must be unique globally within AWS.
    Type: String 

Resources:
  S3BucketForGlueETLProject:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketForETLProject
      Tags:
        - Key: "Project"
          Value: "AWSGlueETL"

  GlueIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueETLRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: GlueETLServicePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:*
                  - lakeformation:*
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListAllMyBuckets
                  - s3:GetBucketAcl
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeRouteTables
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcAttribute
                  - iam:ListRolePolicies
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Effect: Allow
                Action: 
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: 
                  - !GetAtt S3BucketForGlueETLProject.Arn
                  - !Join 
                    - ''
                    - - !GetAtt S3BucketForGlueETLProject.Arn
                      - /*
              - Effect: Allow 
                Action: 
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*:/aws-glue/*
              - Effect: Allow
                Action: 
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource: 
                  - arn:aws:ec2:*:*:network-interface/*
                  - arn:aws:ec2:*:*:security-group/*
                  - arn:aws:ec2:*:*:instance/*
                Condition: 
                  ForAllValues:StringEquals:
                    aws:TagKeys:
                    - aws-glue-service-resource

Outputs:
  S3Bucket:
    Description: A reference to the created S3 bucket
    Value: !Ref S3BucketForGlueETLProject
